name: "Sokoban comunista"
on:
  push:
    branches:
    - main

env:
  GODOT_VERSION: 4.6.0
  USER_VERSION: "1.0.${{ github.run_number }}"

jobs:
  build-desktop-clients:
    name: Export Game Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [windows, linux]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      
      - uses: chickensoft-games/setup-godot@v2
        name: Setup Godot
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          include-templates: true

      - name: Prepare dist 
        run: mkdir -p dist/${{ matrix.target }}

      - name: Export release
        run: godot --headless --export-release ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: sokoban-comunista-${{ matrix.target }}-build
          path: dist/${{ matrix.target }}/
  